function xbodemaglin(sys,linewidth,sw_linestyle,freq_Hz)
% sys: cell array
%
%   Xu Chen  
%    
% 2011-04-26

ni = nargin;
error( nargchk(1, 4, ni) );
if ni<4
    SW_FREQ = 0;
else
    SW_FREQ = 1;
end
if ni<3
    sw_linestyle = 'linestyleOn';
end
if ni<2
    linewidth = 1.5;
end
if ni<1
    error('No inputs')
end

% edit rgb
linecolor = {...
    'b','r',[0 0.5 0],'m',[0 0.75 0.75],[0.87 0.49 0],...
    'b','r',[0 0.5 0],'m',[0 0.75 0.75],[0.87 0.49 0],...
    'b','r',[0 0.5 0],'m',[0 0.75 0.75],[0.87 0.49 0],...
    'b','r',[0 0.5 0],'m',[0 0.75 0.75],[0.87 0.49 0],...
    'b','r',[0 0.5 0],'m',[0 0.75 0.75],[0.87 0.49 0],...
    'b','r',[0 0.5 0],'m',[0 0.75 0.75],[0.87 0.49 0],...
    'b','r',[0 0.5 0],'m',[0 0.75 0.75],[0.87 0.49 0],...
    'b','r',[0 0.5 0],'m',[0 0.75 0.75],[0.87 0.49 0],...
    'b','r',[0 0.5 0],'m',[0 0.75 0.75],[0.87 0.49 0],...
    'b','r',[0 0.5 0],'m',[0 0.75 0.75],[0.87 0.49 0],...
    'b','r',[0 0.5 0],'m',[0 0.75 0.75],[0.87 0.49 0]};
% linecolor = {...    
%     rgb('Blue'),rgb('Red'),rgb('Cyan'),rgb('Magenta'),rgb('Orange'),rgb('DeepPink'),...
%     rgb('Blue'),rgb('Red'),rgb('LightGreen'),rgb('Magenta'),rgb('Orange'),rgb('Black'),...
%     rgb('Blue'),rgb('Red'),rgb('DarkGreen'),rgb('Magenta'),rgb('Orange'),rgb('Black'),...
%     rgb('Blue'),rgb('Red'),rgb('DarkGreen'),rgb('Magenta'),rgb('Orange'),rgb('Black'),...
%     rgb('Blue'),rgb('Red'),rgb('DarkGreen'),rgb('Magenta'),rgb('Orange'),rgb('Black'),...
%     rgb('Blue'),rgb('Red'),rgb('DarkGreen'),rgb('Magenta'),rgb('Orange'),rgb('Black'),...
%     rgb('Blue'),rgb('Red'),rgb('DarkGreen'),rgb('Magenta'),rgb('Orange'),rgb('Black'),...
%     rgb('Blue'),rgb('Red'),rgb('DarkGreen'),rgb('Magenta'),rgb('Orange'),rgb('Black'),...
%     rgb('Blue'),rgb('Red'),rgb('DarkGreen'),rgb('Magenta'),rgb('Orange'),rgb('Black'),...
%     rgb('Blue'),rgb('Red'),rgb('DarkGreen'),rgb('Magenta'),rgb('Orange'),rgb('Black'),...
%     rgb('Blue'),rgb('Red'),rgb('DarkGreen'),rgb('Magenta'),rgb('Orange'),rgb('Black'),...
%     rgb('Blue'),rgb('Red'),rgb('DarkGreen'),rgb('Magenta'),rgb('Orange'),rgb('Black')};
% linecolor = {'b','r','m','k','c','g',...
%     'b','r','m','k','c','g',...
%     'b','r','m','k','c','g',...
%     'b','r','m','k','c','g',...
%     'b','r','m','k','c','g',...
%     'b','r','m','k','c','g',...
%     'b','r','m','k','c','g',...
%     'b','r','m','k','c','g',...
%     'b','r','m','k','c','g',...
%     'b','r','m','k','c','g',...
%     'b','r','m','k','c','g'};
if strncmpi(sw_linestyle,'linestyleOn',11)
linestyle = {'-','--',':','-.',...
    '-','--',':','-.',...
    '-','--',':','-.',...
    '-','--',':','-.',...
    '-','--',':','-.',...
    '-','--',':','-.',...
    '-','--',':','-.',...
    '-','--',':','-.',...
    '-','--',':','-.',...
    '-','--',':','-.',...
    '-','--',':','-.'};
else
    linestyle = {'-','-','-','-',...
    '-','-','-','-',...
    '-','-','-','-',...
    '-','-','-','-',...
    '-','-','-','-',...
    '-','-','-','-',...
    '-','-','-','-',...
    '-','-','-','-',...
    '-','-','-','-',...
    '-','-','-','-',};
end
% if ~exist('linewidth','var')
%     linewidth = 1.5;
% end
N = length(sys);
for ii = 1:N
    if ii == 1
        if SW_FREQ
            freq_Hz_range = logspace(0,log10(freq_Hz*2*pi),1000);
%             freq_Hz_range = logspace(1,log10(freq_Hz*2*pi),1000);
            freq_in_hz = xmaglin(...
                sys{ii},linecolor{ii},linestyle{ii},linewidth,freq_Hz_range);
        else
            freq_in_hz = xmaglin(...
                sys{ii},linecolor{ii},linestyle{ii},linewidth);
        end
    else
        if SW_FREQ
            freq_Hz_range = logspace(0,log10(freq_Hz*2*pi),1000);
%             freq_Hz_range = logspace(1,log10(freq_Hz*2*pi),1000);
            xmaglin(...
                sys{ii},linecolor{ii},linestyle{ii},linewidth,freq_Hz_range);
        else
            xmaglin(...
                sys{ii},linecolor{ii},linestyle{ii},linewidth,freq_in_hz);
        end
    end
    hold on
end
set( gca, 'xlim',  [min(freq_in_hz) max(freq_in_hz)]);
